Tool:
  WOODEN_PICKAXE: 0.13
  STONE_PICKAXE: 0.25
  IRON_PICKAXE: 0.375
  GOLDEN_PICKAXE: 0.5
  DIAMOND_PICKAXE: 0.6

  WOODEN_SHOVEL: 0.13
  STONE_SHOVEL: 0.25
  IRON_SHOVEL: 0.375
  GOLDEN_SHOVEL: 0.5
  DIAMOND_SHOVEL: 0.6

  WOODEN_AXE: 0.13
  STONE_AXE: 0.25
  IRON_AXE: 0.375
  GOLDEN_AXE: 0.5
  DIAMOND_AXE: 0.6

Material:
  ACACIA_BUTTON: 0.5
  ACACIA_DOOR: 3.0
  ACACIA_FENCE: 2.0
  ACACIA_FENCE_GATE: 2.0
  ACACIA_LEAVES: 0.2
  ACACIA_LOG: 2.0
  ACACIA_PLANKS: 2.0
  ACACIA_PRESSURE_PLATE: 0.5
  ACACIA_SAPLING: 0.0
  ACACIA_SLAB: 2.0
  ACACIA_STAIRS: 2.0
  ACACIA_TRAPDOOR: 3.0
  ACACIA_WOOD: 2.0
  ACTIVATOR_RAIL: 0.7
  AIR: 0.0
  ALLIUM: 0.0
  ANDESITE: 1.5
  ANVIL: 5.0
  ATTACHED_MELON_STEM: 0.0
  ATTACHED_PUMPKIN_STEM: 0.0
  AZURE_BLUET: 0.0
  BARRIER: -1.0
  BEACON: 3.0
  BEDROCK: -1.0
  BEETROOTS: 0.0
  BIRCH_BUTTON: 0.5
  BIRCH_DOOR: 3.0
  BIRCH_FENCE: 2.0
  BIRCH_FENCE_GATE: 2.0
  BIRCH_LEAVES: 0.2
  BIRCH_LOG: 2.0
  BIRCH_PLANKS: 2.0
  BIRCH_PRESSURE_PLATE: 0.5
  BIRCH_SAPLING: 0.0
  BIRCH_SLAB: 2.0
  BIRCH_STAIRS: 2.0
  BIRCH_TRAPDOOR: 3.0
  BIRCH_WOOD: 2.0
  BLACK_BANNER: 1.0
  BLACK_BED: 0.2
  BLACK_CARPET: 0.1
  BLACK_CONCRETE: 1.8
  BLACK_CONCRETE_POWDER: 0.5
  BLACK_GLAZED_TERRACOTTA: 1.4
  BLACK_SHULKER_BOX: 2.0
  BLACK_STAINED_GLASS: 0.3
  BLACK_STAINED_GLASS_PANE: 0.3
  BLACK_TERRACOTTA: 1.25
  BLACK_WALL_BANNER: 1.0
  BLACK_WOOL: 0.8
  BLUE_BANNER: 1.0
  BLUE_BED: 0.2
  BLUE_CARPET: 0.1
  BLUE_CONCRETE: 1.8
  BLUE_CONCRETE_POWDER: 0.5
  BLUE_GLAZED_TERRACOTTA: 1.4
  BLUE_ICE: 2.8
  BLUE_ORCHID: 0.0
  BLUE_SHULKER_BOX: 2.0
  BLUE_STAINED_GLASS: 0.3
  BLUE_STAINED_GLASS_PANE: 0.3
  BLUE_TERRACOTTA: 1.25
  BLUE_WALL_BANNER: 1.0
  BLUE_WOOL: 0.8
  BONE_BLOCK: 2.0
  BOOKSHELF: 1.5
  BRAIN_CORAL: 0.0
  BRAIN_CORAL_BLOCK: 1.5
  BRAIN_CORAL_FAN: 0.0
  BRAIN_CORAL_WALL_FAN: 0.0
  BREWING_STAND: 0.5
  BRICKS: 2.0
  BRICK_SLAB: 2.0
  BRICK_STAIRS: 2.0
  BROWN_BANNER: 1.0
  BROWN_BED: 0.2
  BROWN_CARPET: 0.1
  BROWN_CONCRETE: 1.8
  BROWN_CONCRETE_POWDER: 0.5
  BROWN_GLAZED_TERRACOTTA: 1.4
  BROWN_MUSHROOM: 0.0
  BROWN_MUSHROOM_BLOCK: 0.2
  BROWN_SHULKER_BOX: 2.0
  BROWN_STAINED_GLASS: 0.3
  BROWN_STAINED_GLASS_PANE: 0.3
  BROWN_TERRACOTTA: 1.25
  BROWN_WALL_BANNER: 1.0
  BROWN_WOOL: 0.8
  BUBBLE_COLUMN: 0.0
  BUBBLE_CORAL: 0.0
  BUBBLE_CORAL_BLOCK: 1.5
  BUBBLE_CORAL_FAN: 0.0
  BUBBLE_CORAL_WALL_FAN: 0.0
  CACTUS: 0.4
  CAKE: 0.5
  CARROTS: 0.0
  CARVED_PUMPKIN: 1.0
  CAULDRON: 2.0
  CAVE_AIR: 0.0
  CHAIN_COMMAND_BLOCK: -1.0
  CHEST: 2.5
  CHIPPED_ANVIL: 5.0
  CHISELED_QUARTZ_BLOCK: 0.8
  CHISELED_RED_SANDSTONE: 0.8
  CHISELED_SANDSTONE: 0.8
  CHISELED_STONE_BRICKS: 1.5
  CHORUS_FLOWER: 0.4
  CHORUS_PLANT: 0.4
  CLAY: 0.6
  COAL_BLOCK: 5.0
  COAL_ORE: 3.0
  COARSE_DIRT: 0.5
  COBBLESTONE: 2.0
  COBBLESTONE_SLAB: 2.0
  COBBLESTONE_STAIRS: 2.0
  COBBLESTONE_WALL: 2.0
  COBWEB: 4.0
  COCOA: 0.2
  COMMAND_BLOCK: -1.0
  COMPARATOR: 0.0
  CONDUIT: 3.0
  CRACKED_STONE_BRICKS: 1.5
  CRAFTING_TABLE: 2.5
  CREEPER_HEAD: 1.0
  CREEPER_WALL_HEAD: 1.0
  CUT_RED_SANDSTONE: 0.8
  CUT_SANDSTONE: 0.8
  CYAN_BANNER: 1.0
  CYAN_BED: 0.2
  CYAN_CARPET: 0.1
  CYAN_CONCRETE: 1.8
  CYAN_CONCRETE_POWDER: 0.5
  CYAN_GLAZED_TERRACOTTA: 1.4
  CYAN_SHULKER_BOX: 2.0
  CYAN_STAINED_GLASS: 0.3
  CYAN_STAINED_GLASS_PANE: 0.3
  CYAN_TERRACOTTA: 1.25
  CYAN_WALL_BANNER: 1.0
  CYAN_WOOL: 0.8
  DAMAGED_ANVIL: 5.0
  DANDELION: 0.0
  DARK_OAK_BUTTON: 0.5
  DARK_OAK_DOOR: 3.0
  DARK_OAK_FENCE: 2.0
  DARK_OAK_FENCE_GATE: 2.0
  DARK_OAK_LEAVES: 0.2
  DARK_OAK_LOG: 2.0
  DARK_OAK_PLANKS: 2.0
  DARK_OAK_PRESSURE_PLATE: 0.5
  DARK_OAK_SAPLING: 0.0
  DARK_OAK_SLAB: 2.0
  DARK_OAK_STAIRS: 2.0
  DARK_OAK_TRAPDOOR: 3.0
  DARK_OAK_WOOD: 2.0
  DARK_PRISMARINE: 1.5
  DARK_PRISMARINE_SLAB: 1.5
  DARK_PRISMARINE_STAIRS: 1.5
  DAYLIGHT_DETECTOR: 0.2
  DEAD_BRAIN_CORAL: 0.0
  DEAD_BRAIN_CORAL_BLOCK: 1.5
  DEAD_BRAIN_CORAL_FAN: 0.0
  DEAD_BRAIN_CORAL_WALL_FAN: 0.0
  DEAD_BUBBLE_CORAL: 0.0
  DEAD_BUBBLE_CORAL_BLOCK: 1.5
  DEAD_BUBBLE_CORAL_FAN: 0.0
  DEAD_BUBBLE_CORAL_WALL_FAN: 0.0
  DEAD_BUSH: 0.0
  DEAD_FIRE_CORAL: 0.0
  DEAD_FIRE_CORAL_BLOCK: 1.5
  DEAD_FIRE_CORAL_FAN: 0.0
  DEAD_FIRE_CORAL_WALL_FAN: 0.0
  DEAD_HORN_CORAL: 0.0
  DEAD_HORN_CORAL_BLOCK: 1.5
  DEAD_HORN_CORAL_FAN: 0.0
  DEAD_HORN_CORAL_WALL_FAN: 0.0
  DEAD_TUBE_CORAL: 0.0
  DEAD_TUBE_CORAL_BLOCK: 1.5
  DEAD_TUBE_CORAL_FAN: 0.0
  DEAD_TUBE_CORAL_WALL_FAN: 0.0
  DETECTOR_RAIL: 0.7
  DIAMOND_BLOCK: 5.0
  DIAMOND_ORE: 3.0
  DIORITE: 1.5
  DIRT: 0.5
  DISPENSER: 3.5
  DRAGON_EGG: 3.0
  DRAGON_HEAD: 1.0
  DRAGON_WALL_HEAD: 1.0
  DRIED_KELP_BLOCK: 0.5
  DROPPER: 3.5
  EMERALD_BLOCK: 5.0
  EMERALD_ORE: 3.0
  ENCHANTING_TABLE: 5.0
  ENDER_CHEST: 22.5
  END_GATEWAY: -1.0
  END_PORTAL: -1.0
  END_PORTAL_FRAME: -1.0
  END_ROD: 0.0
  END_STONE: 3.0
  END_STONE_BRICKS: 0.8
  FARMLAND: 0.6
  FERN: 0.0
  FIRE: 0.0
  FIRE_CORAL: 0.0
  FIRE_CORAL_BLOCK: 1.5
  FIRE_CORAL_FAN: 0.0
  FIRE_CORAL_WALL_FAN: 0.0
  FLOWER_POT: 0.0
  FROSTED_ICE: 0.5
  FURNACE: 3.5
  GLASS: 0.3
  GLASS_PANE: 0.3
  GLOWSTONE: 0.3
  GOLD_BLOCK: 3.0
  GOLD_ORE: 3.0
  GRANITE: 1.5
  GRASS: 0.0
  GRASS_BLOCK: 0.6
  GRASS_PATH: 0.65
  GRAVEL: 0.6
  GRAY_BANNER: 1.0
  GRAY_BED: 0.2
  GRAY_CARPET: 0.1
  GRAY_CONCRETE: 1.8
  GRAY_CONCRETE_POWDER: 0.5
  GRAY_GLAZED_TERRACOTTA: 1.4
  GRAY_SHULKER_BOX: 2.0
  GRAY_STAINED_GLASS: 0.3
  GRAY_STAINED_GLASS_PANE: 0.3
  GRAY_TERRACOTTA: 1.25
  GRAY_WALL_BANNER: 1.0
  GRAY_WOOL: 0.8
  GREEN_BANNER: 1.0
  GREEN_BED: 0.2
  GREEN_CARPET: 0.1
  GREEN_CONCRETE: 1.8
  GREEN_CONCRETE_POWDER: 0.5
  GREEN_GLAZED_TERRACOTTA: 1.4
  GREEN_SHULKER_BOX: 2.0
  GREEN_STAINED_GLASS: 0.3
  GREEN_STAINED_GLASS_PANE: 0.3
  GREEN_TERRACOTTA: 1.25
  GREEN_WALL_BANNER: 1.0
  GREEN_WOOL: 0.8
  HAY_BLOCK: 0.5
  HEAVY_WEIGHTED_PRESSURE_PLATE: 0.5
  HOPPER: 3.0
  HORN_CORAL: 0.0
  HORN_CORAL_BLOCK: 1.5
  HORN_CORAL_FAN: 0.0
  HORN_CORAL_WALL_FAN: 0.0
  ICE: 0.5
  INFESTED_CHISELED_STONE_BRICKS: 0.0
  INFESTED_COBBLESTONE: 0.0
  INFESTED_CRACKED_STONE_BRICKS: 0.0
  INFESTED_MOSSY_STONE_BRICKS: 0.0
  INFESTED_STONE: 0.0
  INFESTED_STONE_BRICKS: 0.0
  IRON_BARS: 5.0
  IRON_BLOCK: 5.0
  IRON_DOOR: 5.0
  IRON_ORE: 3.0
  IRON_TRAPDOOR: 5.0
  JACK_O_LANTERN: 1.0
  JUKEBOX: 2.0
  JUNGLE_BUTTON: 0.5
  JUNGLE_DOOR: 3.0
  JUNGLE_FENCE: 2.0
  JUNGLE_FENCE_GATE: 2.0
  JUNGLE_LEAVES: 0.2
  JUNGLE_LOG: 2.0
  JUNGLE_PLANKS: 2.0
  JUNGLE_PRESSURE_PLATE: 0.5
  JUNGLE_SAPLING: 0.0
  JUNGLE_SLAB: 2.0
  JUNGLE_STAIRS: 2.0
  JUNGLE_TRAPDOOR: 3.0
  JUNGLE_WOOD: 2.0
  KELP: 0.0
  KELP_PLANT: 0.0
  LADDER: 0.4
  LAPIS_BLOCK: 3.0
  LAPIS_ORE: 3.0
  LARGE_FERN: 0.0
  LAVA: 100.0
  LEVER: 0.5
  LIGHT_BLUE_BANNER: 1.0
  LIGHT_BLUE_BED: 0.2
  LIGHT_BLUE_CARPET: 0.1
  LIGHT_BLUE_CONCRETE: 1.8
  LIGHT_BLUE_CONCRETE_POWDER: 0.5
  LIGHT_BLUE_GLAZED_TERRACOTTA: 1.4
  LIGHT_BLUE_SHULKER_BOX: 2.0
  LIGHT_BLUE_STAINED_GLASS: 0.3
  LIGHT_BLUE_STAINED_GLASS_PANE: 0.3
  LIGHT_BLUE_TERRACOTTA: 1.25
  LIGHT_BLUE_WALL_BANNER: 1.0
  LIGHT_BLUE_WOOL: 0.8
  LIGHT_GRAY_BANNER: 1.0
  LIGHT_GRAY_BED: 0.2
  LIGHT_GRAY_CARPET: 0.1
  LIGHT_GRAY_CONCRETE: 1.8
  LIGHT_GRAY_CONCRETE_POWDER: 0.5
  LIGHT_GRAY_GLAZED_TERRACOTTA: 1.4
  LIGHT_GRAY_SHULKER_BOX: 2.0
  LIGHT_GRAY_STAINED_GLASS: 0.3
  LIGHT_GRAY_STAINED_GLASS_PANE: 0.3
  LIGHT_GRAY_TERRACOTTA: 1.25
  LIGHT_GRAY_WALL_BANNER: 1.0
  LIGHT_GRAY_WOOL: 0.8
  LIGHT_WEIGHTED_PRESSURE_PLATE: 0.5
  LILAC: 0.0
  LILY_PAD: 0.0
  LIME_BANNER: 1.0
  LIME_BED: 0.2
  LIME_CARPET: 0.1
  LIME_CONCRETE: 1.8
  LIME_CONCRETE_POWDER: 0.5
  LIME_GLAZED_TERRACOTTA: 1.4
  LIME_SHULKER_BOX: 2.0
  LIME_STAINED_GLASS: 0.3
  LIME_STAINED_GLASS_PANE: 0.3
  LIME_TERRACOTTA: 1.25
  LIME_WALL_BANNER: 1.0
  LIME_WOOL: 0.8
  MAGENTA_BANNER: 1.0
  MAGENTA_BED: 0.2
  MAGENTA_CARPET: 0.1
  MAGENTA_CONCRETE: 1.8
  MAGENTA_CONCRETE_POWDER: 0.5
  MAGENTA_GLAZED_TERRACOTTA: 1.4
  MAGENTA_SHULKER_BOX: 2.0
  MAGENTA_STAINED_GLASS: 0.3
  MAGENTA_STAINED_GLASS_PANE: 0.3
  MAGENTA_TERRACOTTA: 1.25
  MAGENTA_WALL_BANNER: 1.0
  MAGENTA_WOOL: 0.8
  MAGMA_BLOCK: 0.5
  MELON: 1.0
  MELON_STEM: 0.0
  MOSSY_COBBLESTONE: 2.0
  MOSSY_COBBLESTONE_WALL: 2.0
  MOSSY_STONE_BRICKS: 1.5
  MOVING_PISTON: -1.0
  MUSHROOM_STEM: 0.2
  MYCELIUM: 0.6
  NETHERRACK: 0.4
  NETHER_BRICKS: 2.0
  NETHER_BRICK_FENCE: 2.0
  NETHER_BRICK_SLAB: 2.0
  NETHER_BRICK_STAIRS: 2.0
  NETHER_PORTAL: -1.0
  NETHER_QUARTZ_ORE: 3.0
  NETHER_WART: 0.0
  NETHER_WART_BLOCK: 1.0
  NOTE_BLOCK: 0.8
  OAK_BUTTON: 0.5
  OAK_DOOR: 3.0
  OAK_FENCE: 2.0
  OAK_FENCE_GATE: 2.0
  OAK_LEAVES: 0.2
  OAK_LOG: 2.0
  OAK_PLANKS: 2.0
  OAK_PRESSURE_PLATE: 0.5
  OAK_SAPLING: 0.0
  OAK_SLAB: 2.0
  OAK_STAIRS: 2.0
  OAK_TRAPDOOR: 3.0
  OAK_WOOD: 2.0
  OBSERVER: 3.0
  OBSIDIAN: 50.0
  ORANGE_BANNER: 1.0
  ORANGE_BED: 0.2
  ORANGE_CARPET: 0.1
  ORANGE_CONCRETE: 1.8
  ORANGE_CONCRETE_POWDER: 0.5
  ORANGE_GLAZED_TERRACOTTA: 1.4
  ORANGE_SHULKER_BOX: 2.0
  ORANGE_STAINED_GLASS: 0.3
  ORANGE_STAINED_GLASS_PANE: 0.3
  ORANGE_TERRACOTTA: 1.25
  ORANGE_TULIP: 0.0
  ORANGE_WALL_BANNER: 1.0
  ORANGE_WOOL: 0.8
  OXEYE_DAISY: 0.0
  PACKED_ICE: 0.5
  PEONY: 0.0
  PETRIFIED_OAK_SLAB: 2.0
  PINK_BANNER: 1.0
  PINK_BED: 0.2
  PINK_CARPET: 0.1
  PINK_CONCRETE: 1.8
  PINK_CONCRETE_POWDER: 0.5
  PINK_GLAZED_TERRACOTTA: 1.4
  PINK_SHULKER_BOX: 2.0
  PINK_STAINED_GLASS: 0.3
  PINK_STAINED_GLASS_PANE: 0.3
  PINK_TERRACOTTA: 1.25
  PINK_TULIP: 0.0
  PINK_WALL_BANNER: 1.0
  PINK_WOOL: 0.8
  PISTON: 0.5
  PISTON_HEAD: 0.5
  PLAYER_HEAD: 1.0
  PLAYER_WALL_HEAD: 1.0
  PODZOL: 0.5
  POLISHED_ANDESITE: 1.5
  POLISHED_DIORITE: 1.5
  POLISHED_GRANITE: 1.5
  POPPY: 0.0
  POTATOES: 0.0
  POTTED_ACACIA_SAPLING: 0.0
  POTTED_ALLIUM: 0.0
  POTTED_AZURE_BLUET: 0.0
  POTTED_BIRCH_SAPLING: 0.0
  POTTED_BLUE_ORCHID: 0.0
  POTTED_BROWN_MUSHROOM: 0.0
  POTTED_CACTUS: 0.0
  POTTED_DANDELION: 0.0
  POTTED_DARK_OAK_SAPLING: 0.0
  POTTED_DEAD_BUSH: 0.0
  POTTED_FERN: 0.0
  POTTED_JUNGLE_SAPLING: 0.0
  POTTED_OAK_SAPLING: 0.0
  POTTED_ORANGE_TULIP: 0.0
  POTTED_OXEYE_DAISY: 0.0
  POTTED_PINK_TULIP: 0.0
  POTTED_POPPY: 0.0
  POTTED_RED_MUSHROOM: 0.0
  POTTED_RED_TULIP: 0.0
  POTTED_SPRUCE_SAPLING: 0.0
  POTTED_WHITE_TULIP: 0.0
  POWERED_RAIL: 0.7
  PRISMARINE: 1.5
  PRISMARINE_BRICKS: 1.5
  PRISMARINE_BRICK_SLAB: 1.5
  PRISMARINE_BRICK_STAIRS: 1.5
  PRISMARINE_SLAB: 1.5
  PRISMARINE_STAIRS: 1.5
  PUMPKIN: 1.0
  PUMPKIN_STEM: 0.0
  PURPLE_BANNER: 1.0
  PURPLE_BED: 0.2
  PURPLE_CARPET: 0.1
  PURPLE_CONCRETE: 1.8
  PURPLE_CONCRETE_POWDER: 0.5
  PURPLE_GLAZED_TERRACOTTA: 1.4
  PURPLE_SHULKER_BOX: 2.0
  PURPLE_STAINED_GLASS: 0.3
  PURPLE_STAINED_GLASS_PANE: 0.3
  PURPLE_TERRACOTTA: 1.25
  PURPLE_WALL_BANNER: 1.0
  PURPLE_WOOL: 0.8
  PURPUR_BLOCK: 1.5
  PURPUR_PILLAR: 1.5
  PURPUR_SLAB: 2.0
  PURPUR_STAIRS: 1.5
  QUARTZ_BLOCK: 0.8
  QUARTZ_PILLAR: 0.8
  QUARTZ_SLAB: 2.0
  QUARTZ_STAIRS: 0.8
  RAIL: 0.7
  REDSTONE_BLOCK: 5.0
  REDSTONE_LAMP: 0.3
  REDSTONE_ORE: 3.0
  REDSTONE_TORCH: 0.0
  REDSTONE_WALL_TORCH: 0.0
  REDSTONE_WIRE: 0.0
  RED_BANNER: 1.0
  RED_BED: 0.2
  RED_CARPET: 0.1
  RED_CONCRETE: 1.8
  RED_CONCRETE_POWDER: 0.5
  RED_GLAZED_TERRACOTTA: 1.4
  RED_MUSHROOM: 0.0
  RED_MUSHROOM_BLOCK: 0.2
  RED_NETHER_BRICKS: 2.0
  RED_SAND: 0.5
  RED_SANDSTONE: 0.8
  RED_SANDSTONE_SLAB: 2.0
  RED_SANDSTONE_STAIRS: 0.8
  RED_SHULKER_BOX: 2.0
  RED_STAINED_GLASS: 0.3
  RED_STAINED_GLASS_PANE: 0.3
  RED_TERRACOTTA: 1.25
  RED_TULIP: 0.0
  RED_WALL_BANNER: 1.0
  RED_WOOL: 0.8
  REPEATER: 0.0
  REPEATING_COMMAND_BLOCK: -1.0
  ROSE_BUSH: 0.0
  SAND: 0.5
  SANDSTONE: 0.8
  SANDSTONE_SLAB: 2.0
  SANDSTONE_STAIRS: 0.8
  SEAGRASS: 0.0
  SEA_LANTERN: 0.3
  SEA_PICKLE: 0.0
  SHULKER_BOX: 2.0
  SIGN: 1.0
  SKELETON_SKULL: 1.0
  SKELETON_WALL_SKULL: 1.0
  SLIME_BLOCK: 0.0
  SMOOTH_QUARTZ: 2.0
  SMOOTH_RED_SANDSTONE: 2.0
  SMOOTH_SANDSTONE: 2.0
  SMOOTH_STONE: 2.0
  SNOW: 0.1
  SNOW_BLOCK: 0.2
  SOUL_SAND: 0.5
  SPAWNER: 5.0
  SPONGE: 0.6
  SPRUCE_BUTTON: 0.5
  SPRUCE_DOOR: 3.0
  SPRUCE_FENCE: 2.0
  SPRUCE_FENCE_GATE: 2.0
  SPRUCE_LEAVES: 0.2
  SPRUCE_LOG: 2.0
  SPRUCE_PLANKS: 2.0
  SPRUCE_PRESSURE_PLATE: 0.5
  SPRUCE_SAPLING: 0.0
  SPRUCE_SLAB: 2.0
  SPRUCE_STAIRS: 2.0
  SPRUCE_TRAPDOOR: 3.0
  SPRUCE_WOOD: 2.0
  STICKY_PISTON: 0.5
  STONE: 1.5
  STONE_BRICKS: 1.5
  STONE_BRICK_SLAB: 2.0
  STONE_BRICK_STAIRS: 1.5
  STONE_BUTTON: 0.5
  STONE_PRESSURE_PLATE: 0.5
  STONE_SLAB: 2.0
  STRIPPED_ACACIA_LOG: 2.0
  STRIPPED_ACACIA_WOOD: 2.0
  STRIPPED_BIRCH_LOG: 2.0
  STRIPPED_BIRCH_WOOD: 2.0
  STRIPPED_DARK_OAK_LOG: 2.0
  STRIPPED_DARK_OAK_WOOD: 2.0
  STRIPPED_JUNGLE_LOG: 2.0
  STRIPPED_JUNGLE_WOOD: 2.0
  STRIPPED_OAK_LOG: 2.0
  STRIPPED_OAK_WOOD: 2.0
  STRIPPED_SPRUCE_LOG: 2.0
  STRIPPED_SPRUCE_WOOD: 2.0
  STRUCTURE_BLOCK: -1.0
  STRUCTURE_VOID: 0.0
  SUGAR_CANE: 0.0
  SUNFLOWER: 0.0
  TALL_GRASS: 0.0
  TALL_SEAGRASS: 0.0
  TERRACOTTA: 1.25
  TNT: 0.0
  TORCH: 0.0
  TRAPPED_CHEST: 2.5
  TRIPWIRE: 0.0
  TRIPWIRE_HOOK: 0.0
  TUBE_CORAL: 0.0
  TUBE_CORAL_BLOCK: 1.5
  TUBE_CORAL_FAN: 0.0
  TUBE_CORAL_WALL_FAN: 0.0
  TURTLE_EGG: 0.5
  VINE: 0.2
  VOID_AIR: 0.0
  WALL_SIGN: 1.0
  WALL_TORCH: 0.0
  WATER: 100.0
  WET_SPONGE: 0.6
  WHEAT: 0.0
  WHITE_BANNER: 1.0
  WHITE_BED: 0.2
  WHITE_CARPET: 0.1
  WHITE_CONCRETE: 1.8
  WHITE_CONCRETE_POWDER: 0.5
  WHITE_GLAZED_TERRACOTTA: 1.4
  WHITE_SHULKER_BOX: 2.0
  WHITE_STAINED_GLASS: 0.3
  WHITE_STAINED_GLASS_PANE: 0.3
  WHITE_TERRACOTTA: 1.25
  WHITE_TULIP: 0.0
  WHITE_WALL_BANNER: 1.0
  WHITE_WOOL: 0.8
  WITHER_SKELETON_SKULL: 1.0
  WITHER_SKELETON_WALL_SKULL: 1.0
  YELLOW_BANNER: 1.0
  YELLOW_BED: 0.2
  YELLOW_CARPET: 0.1
  YELLOW_CONCRETE: 1.8
  YELLOW_CONCRETE_POWDER: 0.5
  YELLOW_GLAZED_TERRACOTTA: 1.4
  YELLOW_SHULKER_BOX: 2.0
  YELLOW_STAINED_GLASS: 0.3
  YELLOW_STAINED_GLASS_PANE: 0.3
  YELLOW_TERRACOTTA: 1.25
  YELLOW_WALL_BANNER: 1.0
  YELLOW_WOOL: 0.8
  ZOMBIE_HEAD: 1.0
  ZOMBIE_WALL_HEAD: 1.0
